name: body_part_selector
description: A beautiful selector for different body parts
version: 0.0.2
homepage: https://www.fyzo.de
repository: https://github.com/fyzio/body_part_selector
issue_tracker: https://github.com/fyzio/body_part_selector

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.0
  touchable: ^1.0.2
  freezed_annotation: ^2.0.3
  rotation_stage: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - packages/body_part_selector/m_front.svg
    - packages/body_part_selector/m_left.svg
    - packages/body_part_selector/m_back.svg
    - packages/body_part_selector/m_right.svg
